baseURL = 'https://giro-dev.github.io/criteria-filter/'
languageCode = 'en-us'
title = 'criteria-filter'
theme = 'criteria-docs'

[params]
  author = 'Agiro'
  description = 'Dynamic, declarative filtering for Spring Boot and beyond.'
  github = 'https://github.com/giro-dev/criteria-filter'
  version = '0.1.0-SNAPSHOT'

[menu]
  [[menu.main]]
    name = 'Docs'
    url = '/docs/'
    weight = 10
  [[menu.main]]
    name = 'Demo'
    url = '/demo/'
    weight = 20
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = true
    style = 'github'
